apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nwxu
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-code-with-quarkus-nwxu
    app.kubernetes.io/part-of: test-rhtap-91-app
  name: devfile-sample-code-with-quarkus-nwxu
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nwxu
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: devfile-sample-code-with-quarkus-nwxu
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-91-tenant/test-rhtap-91-app/devfile-sample-code-with-quarkus-nwxu@sha256:7ae33bec4c6ae675c07f34e2bf94650c20d2850a2c9a63312674fd729ad576c2
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
